
// changelog pair semantics: lone weak marker is prose, signal is 2+ weak per comment run or one strong marker
export const CHANGELOG_STRONG =
  /\bwas\b[^,.;\n]{0,60},\s*(?:and\s+)?now\b|\bthis fixes\b|\bthis fix\b|\bmust take over\b|broke, so|\b(?:before|prior\s+to|after|since)\s+this\s+(?:change|refactor|rewrite)\b(?!\s+(?:of|request)\b)|\bthe\s+old\b[^,.;\n]{0,40}(?<!\b(?:is|are|was|were|be|been|being)\s)\b(?:kept|behaved|returned|assumed|treated|held|ignored|skipped)\b(?!\s+(?:for|by|as|to|with|in|on|from|like|than|if|when|whenever|unless|until|during|while|over|under|across|through|via|without|within|between|among|against|per|onto|upon|about|after|before|since|despite|except|into|of|at|because|although|though|whereas|whether|around)\b)(?!\s+[\w-]{1,20}\s+by\b)|(?:(?<![\w)\]]\s)|(?<=\b(?:and|but|since|because|when|while|as|earlier|previously|originally|now|then|so|also|however|rem)\s))\b(?:we|they|it|this)\s+used to\b|(?<![а-яё])(?:до|после)\s+(?:этого\s+изменения|этой\s+правки)|(?<![а-яё])(?:стар(?:ый|ая|ое|ые|ого|ому|ым|ом|ой|ую|ых|ыми)|прежн(?:ий|яя|ее|ие|его|ему|им|ем|ей|юю|их|ими))[^,.;\n]{0,40}(?:держал[аои]?|возвращал[аои]?|считал[аои]?|обрабатывал[аои]?|игнорировал[аои]?|пропускал[аои]?|вел[аои]?|вёл)(?![а-яё])(?!\s+бы(?![а-яё]))|\bused to\b[^,.;\n]{0,50}\b(?:has|have)\s+been\s+(?:removed|deleted|replaced|dropped)\b/i
export const CHANGELOG_WEAK =
  /(?<![а-яё])(?:было|стало|раньше|вместо|теперь)(?![а-яё])|\bnow we\b|\bpreviously\b|\binstead of\b|\bno longer\b|(?<![a-zäöüß])(?:stattdessen|nicht mehr|früher war|war vorher)(?![a-zäöüß])|\bau lieu de\b|(?<![a-zéèêàùç])(?:auparavant|désormais)(?![a-zéèêàùç])|\ben lugar de\b|\bantes era\b|\bya no\b|\banteriormente\b/gi
export const weakMarkerHits = (text) => (text.match(CHANGELOG_WEAK) ?? []).length
export const GEN_NAME_SAFE =
  /\.(?:g|g\.i|freezed|gr|chopper|pb|pbenum|pbjson|pbgrpc|pbserver)\.dart$|_pb2(?:_grpc)?\.py$|_pb2\.pyi$|_pb\.go$|_grpc\.pb\.go$|\.pb\.(?:cc|h|hpp|cpp)$|_grpc\.pb\.(?:cc|h)$|\.pb\.mojom\.(?:cc|h)$|zz_generated\.|_string\.go$|\.sql\.go$|\.querier\.go$|\.Designer\.cs$|\.g\.i\.cs$|AssemblyAttributes\.cs$|^GlobalUsings(?:\.g)?\.cs$|\.min\.[cm]?js$|\.min\.css$|\.bundle\.js$/i
export const GEN_HEADER_STRICT =
  /@generated\b|code generated by [^\n]*do not edit|generated code - do not modify by hand|<auto-generated|automatically generated by rust-bindgen|@generated by prost-build|@javax\.annotation\.(?:processing\.)?Generated\(|generated by openapi-generator|code generated by sqlc/i
export const GEN_HEADER_LAX = [/generat|codegen/i, /do not (?:edit|modify)|do-not-edit/i]
export const STEP_NUMBERED = /^(?:step\s+\d+|шаг\s+\d+|schritt\s+\d+|(?<![a-zéèêàùç])étape\s+\d+|paso\s+\d+|\d+\.)/i
export const STEP_WORD = /^(?:step\s+\d+|шаг\s+\d+|schritt\s+\d+|(?<![a-zéèêàùç])étape\s+\d+|paso\s+\d+)/i
export const DIVIDER_CHARS = /^[-=#*\s─-╿]{6,}$/
export const MARKDOWN_BOLD = /^\*\*/
export const MARKDOWN_LIST = /^-\s+\S/
export const MARKDOWN_TABLE = /^\|.+\|.+\|/
export const THIS_OPENER =
  /^(?:this\s+(?:function|class|method|component)\b|(?:эт[ао]т?\s+|данн(?:ая|ый)\s+)(?:функци[а-яё]*|класс[а-яё]*|метод[а-яё]*|компонент[а-яё]*)|diese[rs]?\s+(?:funktion|klasse|methode|komponente)|cett[ee]\s+(?:fonction|classe|méthode|composant)|est[ae]\s+(?:función|clase|método|componente))/i
export const AI_PLAN_REFERENCE =
  /\bper\s+the\s+(?:spec|task|ticket|prompt|plan)\b|\bstep\s+\d+\s+of\s+the\s+plan\b|\bas\s+per\s+requirements?\b|(?<![а-яё])(?:согласно\s+тз|по\s+плану|шаг\s+\d+\s+плана|согласно\s+спецификации)(?![а-яё])|(?<![a-zäöüß])(?:gemäß\s+(?:spec|plan)|laut\s+anforderungen?)(?![a-zäöüß])|(?<![a-zéèêàùç])(?:selon\s+(?:la\s+spec|le\s+plan))(?![a-zéèêàùç])|(?<![a-záéíóúñ])(?:conforme\s+a\s+la\s+especificación|según\s+el\s+plan)(?![a-záéíóúñ])/i
export const AI_PLAN_ACK =
  /^as\s+(?:instructed|requested)\b|^the\s+user\s+asked\b|(?<![а-яё])(?:как\s+было\s+запрошено|пользователь\s+попросил)(?![а-яё])|(?<![a-zäöüß])(?:wie\s+angewiesen)(?![a-zäöüß])|(?<![a-zéèêàùç])(?:comme\s+demandé(?:e|s|es)?)(?![a-zéèêàùç])|(?<![a-záéíóúñ])(?:como\s+se\s+indicó)(?![a-záéíóúñ])/i
export const TODO_WORD = /\b(?:todo|fixme|xxx)\b/i
export const AI_VOCAB_TOKENS =
  /\b(?:additionally|boasts|bolstered|crucial|delve|emphasizing|enduring|garner|intricate|intricacies|interplay|meticulously|meticulous|pivotal|tapestry|testament|vibrant|fostering|showcasing)\b/gi
export const TICKET_REF = /[A-Z]+-\d+/
export const CITATION_AUTHOR_YEAR =
  /\([A-Z][\w'’-]*(?:,\s*\d{4}|\s+et\s+al\.?,?\s*\d{4})\)|\([А-ЯЁ][а-яё-]*(?:,\s*\d{4}|\s+и\s+др\.?,?\s*\d{4})\)/
export const CITATION_ARXIV = /\barXiv:\s*\d{4}\.\d{4,5}(?:v\d+)?\b/i
export const isResearchCitation = (text) => CITATION_AUTHOR_YEAR.test(text) || CITATION_ARXIV.test(text)
export const ISSUE_LINK = /https?:\/\/\S+|#\d+/
export const ADVISORY_REF = /\b(?:CVE|GHSA)-/i
export const LONG_LINK = /https?:\/\/\S{30,}/
export const CROSS_FILE_REF = /(?<![\w@:./\\-])((?:[\w.-]+[\/\\])*)([\w-]+)\.([A-Za-z]{1,5}):(\d+)/
export const CODE_REF_EXT = new Set(
  "ts tsx js jsx mjs cjs mts cts py pyi rb go rs java kt kts cs c h cc cpp hpp hh swift dart scala php sh bash ps1 sql yaml yml toml json md mdx html css scss less vue svelte astro lua ex exs erl hrl clj cljs fs fsx pl pm r jl nim zig gradle proto tf nix v sv qml coffee tex vim bat mk cmake bzl sol res".split(
    " ",
  ),
)
export const isCrossFileRef = (text) => {
  const m = CROSS_FILE_REF.exec(text)
  if (m === null) return false
  return m[1] !== "" || CODE_REF_EXT.has(m[3].toLowerCase())
}
export const OBVIOUS_STOPWORDS = new Set(
  (
    "a an the this that these those is are was were be been being of to in on for with and or not no it its if then else from by as at we you they do does did has have had will would can could may might there their them he she his her him но и или не в на для с от до по как что же бы ли уже ещё при над под без через между его её их мы вы он она они оно этот эта это эти тот там тут"
  ).split(" "),
)
export const OBVIOUS_WHY =
  /because|since|otherwise|unless|until|so that|in case|workaround|invariant|constraint|intentionally|deliberately|required|\bmust\b|\bshould\b|\bcannot\b|\bavoid\b|\bonly\b|\butc\b|\bgmt\b|\bms\b|millisecond|second|т\.?\s*к\.|так как|потому что|чтобы|иначе|если|пока|должн|нужно|надо|обязательн|нельзя|воркэраунд|инвариант|ограничен|осторожн|намеренн|специальн|требует|только|миллисекунд|секунд/i
export const WHY_MARKERS =
  /\bbecause\b|\bsince\b|\botherwise\b|\bworkarounds?\b|\bcaveats?\b|\bto\s+avoid\b|\bby\s+design\b|\bhowever\b|\btrade-?offs?\b|\bfails?\s+when\b|\be\.g\.|\binvariants?\b|\bnote:|(?<![а-яё])(?:потому\s+что|иначе|воркэраунд|обход|чтобы\s+избежать|специально|напр\.)(?![а-яё])|(?<![a-zäöüß])(?:denn|sonst|um\s+zu\s+vermeiden)(?![a-zäöüß])|(?<![a-zéèêàùç])(?:car|sinon|contournement|pour\s+éviter)(?![a-zéèêàùç])|(?<![a-záéíóúñ])(?:porque|si\s+no|solución\s+alternativa|para\s+evitar)(?![a-záéíóúñ])/i
export const OBVIOUS_WORD_SPLIT = /[^a-zа-яё0-9]+/
export const camelSplit = (line) => line.replace(/([a-z0-9])(?=[A-Z])/g, "$1 ")
export const commentContentWords = (text) =>
  text
    .toLowerCase()
    .split(OBVIOUS_WORD_SPLIT)
    .filter((w) => w !== "" && /[a-zа-яё]/.test(w) && !OBVIOUS_STOPWORDS.has(w))
export const codeTokenSet = (line) =>
  new Set(
    camelSplit(line)
      .toLowerCase()
      .split(OBVIOUS_WORD_SPLIT)
      .filter((w) => w !== ""),
  )
export const isObviousComment = (text, codeLine) => {
  if (OBVIOUS_WHY.test(text) || CJK_ANY.test(text)) return false
  const words = commentContentWords(text)
  if (words.length === 0 || words.length > 6) return false
  const tokens = codeTokenSet(codeLine)
  const hits = words.filter((w) => tokens.has(w)).length
  return hits >= (text.includes(",") ? 2 : 1)
}
export const CP = (...cps) => String.fromCodePoint(...cps)
export const BS = CP(0x5c)
export const STRIP_INVISIBLE = new RegExp("[" + CP(0x200b) + "-" + CP(0x200f) + CP(0xfeff) + "]", "g")
export const CJK = "[\\u2E80-\\u2EFF\\u3400-\\u4DBF\\u4E00-\\u9FFF\\uF900-\\uFAFF\\u3040-\\u30FF\\uAC00-\\uD7AF]"
export const CJK_ANY = new RegExp(CJK)
export const LATIN = "[A-Za-z0-9_]"
export const CJK_ADJACENT = new RegExp(CJK + LATIN + "|" + LATIN + CJK)
export const ZERO_WIDTH = new RegExp("[" + CP(0x200b, 0x200c, 0x2060) + "]|" + BS + BS + "u200[bBcC]|" + BS + BS + "u2060")
export const ZWJ_ESCAPE = new RegExp(BS + BS + "u200[dD]")
export const FEFF_ESCAPE = new RegExp(BS + BS + "u[fF][eE][fF][fF]")
export const FEFF_CHAR = CP(0xfeff)
export const ZWJ_CHAR = CP(0x200d)
export const EMOJI = new RegExp(
  "[" +
    [
      [0x2600, 0x27bf],
      [0x1f300, 0x1f5ff],
      [0x1f600, 0x1f64f],
      [0x1f680, 0x1f6c5],
      [0x1f900, 0x1f9ff],
      [0x1f3fb, 0x1f3ff],
    ]
      .map(([a, b]) => CP(a) + "-" + CP(b))
      .join("") +
    "]",
  "u",
)
export const BIDI = new RegExp(
  "[" + CP(0x202a, 0x202b, 0x202c, 0x202d, 0x202e, 0x2066, 0x2067, 0x2068, 0x2069) + "]|" + BS + BS + "u202[a-eA-E]|" + BS + BS + "u206[6-9]",
)
export const BIDI_MARK = new RegExp("[" + CP(0x200e, 0x200f) + "]|" + BS + BS + "u200[eEfF]")
export const hasBadZwj = (line) => {
  if (ZWJ_ESCAPE.test(line)) return true
  const chars = [...line]
  for (let k = 0; k < chars.length; k++) {
    if (chars[k] !== ZWJ_CHAR) continue
    if (!EMOJI.test(chars[k - 1] ?? "") || !EMOJI.test(chars[k + 1] ?? "")) return true
  }
  return false
}
export const hasBadFeff = (line, i) => {
  if (FEFF_ESCAPE.test(line)) return true
  const idx = line.indexOf(FEFF_CHAR)
  if (idx === -1) return false
  if (i === 0 && idx === 0) return line.indexOf(FEFF_CHAR, 1) !== -1
  return true
}
export const zeroWidthHit = (line, i) => ZERO_WIDTH.test(line) || hasBadZwj(line) || hasBadFeff(line, i)
export const SUPPRESS_NEXT = /stop-ai-slop-ignore-next-line\b(.*)$/
export const SUPPRESS_LINE = /stop-ai-slop-ignore-line\b(.*)$/
export const SUPPRESS_FILE = /stop-ai-slop-ignore-file\b(.*)$/
export const SUPPRESS_ANY = /stop-ai-slop-ignore-(?:next-line|line|file)\b/

export const rulesOfTail = (tail) => {
  const ids = tail.split("--")[0].trim().split(/\s+/).filter((w) => w !== "")
  return ids.length === 0 ? null : new Set(ids)
}
export const LICENSE_HEAD = /^(?:\/\/+|\/\*+|\*+|\(\*+|<!--+|#+|;+|--+)\s*(?:copyright|licensed?|SPDX)/i
export const GO_DECL_NAME = /^\s*(?:func\s+(?:\([^)]*\)\s*)?|type\s+|const\s+|var\s+)(\w+)/
export const isLicenseRun = (runLines) =>
  runLines.slice(0, 3).some((l) => LICENSE_HEAD.test(l.trim())) || runLines.some((l) => l.includes("SPDX-License-Identifier"))
export const STEP_PREFIX_FIX = /^(?:step\s+\d+|шаг\s+\d+|schritt\s+\d+|étape\s+\d+|paso\s+\d+|\d+\.)\s*[:.、)–—-]?\s*/i
export const COMMENT_LEAD_FIX = /^(\s*(?:\/\/+|#+|--+|;+|%+|::+|\.\.+|!|\(\*+|<!--+|\{\{!--?|\{\{!))\s*/
export const BLOCK_OPENER = /^(?:\/\*|<!--|<#|\(\*|###|\{\{!--?|\{\{\/\*|-{2}\[\[|\{-|#\[|=#)/
export const BIDI_CHARS = new RegExp("[" + CP(0x202a, 0x202b, 0x202c, 0x202d, 0x202e, 0x2066, 0x2067, 0x2068, 0x2069) + "]", "g")

// escape-формы — предмет кода; марки U+200E/F легитимны в комментарии, режутся только до commentStart
export function stripBadInvisibles(line, lineIdx, commentStart = Infinity) {
  const chars = [...line]
  const out = []
  let pos = 0
  for (let k = 0; k < chars.length; k++) {
    const cp = chars[k].codePointAt(0)
    const inCode = pos < commentStart
    pos += chars[k].length
    if (cp === 0x200d && EMOJI.test(chars[k - 1] ?? "") && EMOJI.test(chars[k + 1] ?? "")) {
      out.push(chars[k])
      continue
    }
    if (cp === 0xfeff && lineIdx === 0 && k === 0 && line.indexOf(FEFF_CHAR, 1) === -1) {
      out.push(chars[k])
      continue
    }
    const bad =
      (cp >= 0x200b && cp <= 0x200d) ||
      (inCode && (cp === 0x200e || cp === 0x200f)) ||
      cp === 0x2060 ||
      cp === 0xfeff ||
      (cp >= 0x202a && cp <= 0x202e) ||
      (cp >= 0x2066 && cp <= 0x2069)
    if (!bad) out.push(chars[k])
  }
  return out.join("").replace(BIDI_CHARS, "")
}
