import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { pathToFileURL } from "node:url"

const GEN = "Code " + "generated by tool. DO NOT " + "EDIT."
const LAX = ["// " + "generat" + "ed by internal tool", "// " + "do not edit" + " this file"]
const SLOP = "// aaa\n// bbb\nconst x = 1\n"
const CP = (...cps) => String.fromCodePoint(...cps)

export default async function ({ check, runCli, selfRoot }) {
  const mod = await import(pathToFileURL(join(selfRoot, "skill", "scripts", "scan.mjs")).href)
  const ctx = { gitattr: null, cfgPaths: [], scanGenerated: false }
  const classified = (relPath, text) => mod.isGeneratedFile(relPath, text, ctx)

  const own = readFileSync(join(selfRoot, "skill", "scripts", "src", "markers.mjs"), "utf8")
  check(
    "generated-selfref: the module defining the header patterns is not itself exempt",
    classified("skill/scripts/src/markers.mjs", own) === false,
    "markers.mjs classified as generated",
  )

  const work = mkdtempSync(join(tmpdir(), "slop-gate-genhdr-"))
  try {
    writeFileSync(join(work, "quoted.ts"), `export const HEADER = /${GEN.toLowerCase()}/i\n${SLOP}`)
    writeFileSync(join(work, "laxcode.ts"), `const a = "generat" + "codegen"\nconst b = "do not edit"\n${SLOP}`)
    writeFileSync(join(work, "linehdr.ts"), `// ${GEN}\n${SLOP}`)
    writeFileSync(join(work, "blockhdr.ts"), `/*\n * ${GEN}\n */\n${SLOP}`)
    writeFileSync(join(work, "hashhdr.py"), `# ${GEN}\n${SLOP.replace(/\/\/ /g, "# ")}`)
    writeFileSync(join(work, "laxhdr.ts"), LAX.join("\n") + "\n" + SLOP)
    writeFileSync(join(work, "bare.ts"), `// DO NOT EDIT\n${SLOP}`)
    writeFileSync(join(work, "models.g.dart"), SLOP.replace("const x", "final x"))
    writeFileSync(join(work, "baremid.ps1"), "<#\n" + GEN + "\n#>\n# aaa\n# bbb\n$x = 1\n")
    writeFileSync(join(work, "baremid.c"), "/*\n" + GEN + "\n*/\n// aaa\n// bbb\nint x = 1;\n")
    writeFileSync(join(work, "baremid.xml"), "<!--\n" + GEN + "\n-->\n<!-- aaa\nbbb -->\n<x/>\n")
    writeFileSync(join(work, "baremid.hs"), "{-\n" + GEN + "\n-}\n-- aaa\n-- bbb\nmain = return ()\n")
    writeFileSync(join(work, "baremid.lua"), "--[[\n" + GEN + "\n]]\n-- aaa\n-- bbb\nlocal x = 1\n")
    writeFileSync(join(work, "sec.g.dart"), "// " + GEN + "\n// aaa\n// bbb\nfinal s = '" + CP(0x200b) + "'\n")

    const scanOf = (name) => runCli(["scan", name], work)

    const quoted = scanOf("quoted.ts")
    check(
      "generated-header: a pattern quoted in code does not exempt the file",
      quoted.status === 1 && quoted.out.includes("multi-line-comment"),
      `exit ${quoted.status}: ${quoted.out.slice(0, 200)}`,
    )
    const laxcode = scanOf("laxcode.ts")
    check(
      "generated-header: generator words in code identifiers do not exempt the file",
      laxcode.status === 1 && laxcode.out.includes("multi-line-comment"),
      `exit ${laxcode.status}: ${laxcode.out.slice(0, 200)}`,
    )
    const linehdr = scanOf("linehdr.ts")
    check("generated-header: a real line-comment tool header still exempts", linehdr.status === 0, `exit ${linehdr.status}: ${linehdr.out.slice(0, 200)}`)
    const blockhdr = scanOf("blockhdr.ts")
    check("generated-header: a block-comment tool header still exempts", blockhdr.status === 0, `exit ${blockhdr.status}: ${blockhdr.out.slice(0, 200)}`)
    const hashhdr = scanOf("hashhdr.py")
    check("generated-header: a hash-profile tool header still exempts", hashhdr.status === 0, `exit ${hashhdr.status}: ${hashhdr.out.slice(0, 200)}`)
    const laxhdr = scanOf("laxhdr.ts")
    check("generated-header: the lax comment pair still exempts", laxhdr.status === 0, `exit ${laxhdr.status}: ${laxhdr.out.slice(0, 200)}`)
    const bare = scanOf("bare.ts")
    check(
      "generated-header: a bare DO NOT EDIT without a generator word does not exempt",
      bare.status === 1 && bare.out.includes("multi-line-comment"),
      `exit ${bare.status}: ${bare.out.slice(0, 200)}`,
    )
    const named = scanOf("models.g.dart")
    check("generated-header: unique filename suffixes stay exempt", named.status === 0, `exit ${named.status}: ${named.out.slice(0, 200)}`)

    for (const bare of ["baremid.ps1", "baremid.c", "baremid.xml", "baremid.hs", "baremid.lua"]) {
      const res = scanOf(bare)
      check(
        `generated-header: a bare-middle block header still exempts (${bare})`,
        res.status === 0 && !res.out.includes("multi-line-comment"),
        `exit ${res.status}: ${res.out.slice(0, 200)}`,
      )
    }

    const sec = scanOf("sec.g.dart")
    check(
      "generated-security: a zero-width char in an exempt file is still reported",
      sec.status === 1 && sec.out.includes("vend/zero-width-chars") && !sec.out.includes("multi-line-comment"),
      `exit ${sec.status}: ${sec.out.slice(0, 200)}`,
    )
    check(
      "generated-name: unique filename suffixes stay exempt through the direct API",
      classified("models.g.dart", "// " + GEN + "\n") === true,
      "name-based exemption regressed",
    )
  } finally {
    rmSync(work, { recursive: true, force: true })
  }
}
