package whitebite.slop

import io.gitlab.arturbosch.detekt.test.TestConfig
import io.gitlab.arturbosch.detekt.test.lint
import kotlin.test.Test
import kotlin.test.assertEquals

class StopAiSlopCrossCuttingTest {
    private val step = StopAiSlopStepNumbered(TestConfig())

    @Test
    fun `ignore-next-line with the rule id suppresses it`() {
        assertEquals(0, step.lint(lines(ignoreNext("vend/step-numbered"), "// Step 1: run", "val x = 1")).size)
    }

    @Test
    fun `ignore-next-line with another valid rule id does not suppress`() {
        assertEquals(1, step.lint(lines(ignoreNext("long-comment"), "// Step 1: run", "val x = 1")).size)
    }

    @Test
    fun `ignore-next-line with an unknown rule id is inert`() {
        assertEquals(1, step.lint(lines(ignoreNext("vend/long-comment"), "// Step 1: run", "val x = 1")).size)
    }

    @Test
    fun `bare ignore-next-line suppresses everything`() {
        assertEquals(0, step.lint(lines("// stop-ai-slop-ignore-next-line -- probe", "// Step 1: run", "val x = 1")).size)
    }

    @Test
    fun `ignore-file suppresses everything`() {
        assertEquals(0, step.lint(lines(ignoreFileLine(), "// Step 1: run", "val x = 1")).size)
    }

    @Test
    fun `ignore-file text inside a string literal does not suppress`() {
        assertEquals(1, step.lint(lines("val s = \"stop-ai-slop-ignore-file\"", "// Step 1: run", "val x = 1")).size)
    }

    @Test
    fun `ignore-next-line text inside a string literal does not suppress`() {
        assertEquals(1, step.lint(lines("val s = \"stop-ai-slop-ignore-next-line\"", "// Step 1: run", "val x = 1")).size)
    }

    @Test
    fun `ignore-line text inside a string literal does not suppress`() {
        assertEquals(1, step.lint(lines("val s = \"stop-ai-slop-ignore-line\" // Step 1: run")).size)
    }

    @Test
    fun `generated lax header pair exempts slop rules`() {
        assertEquals(0, step.lint(lines("// generated by tool", "// do not edit", "// Step 1: run", "val x = 1")).size)
    }

    @Test
    fun `generated strict header in a comment exempts slop rules`() {
        assertEquals(0, step.lint(lines("// Code generated by tool. DO NOT EDIT.", "// Step 1: run", "val x = 1")).size)
    }

    @Test
    fun `generated marker text inside a string literal does not exempt`() {
        assertEquals(1, step.lint(lines("val note = \"do not edit generated files by hand\"", "// Step 1: run", "val x = 1")).size)
    }

    @Test
    fun `bare do not edit does not exempt`() {
        assertEquals(1, step.lint(lines("// DO NOT EDIT", "// Step 1: run", "val x = 1")).size)
    }

    @Test
    fun `license header does not exempt unrelated findings`() {
        assertEquals(1, step.lint(lines("// Copyright 2024 Foo", "// Step 1: run", "val x = 1")).size)
    }
}
